# To use this file, run `docker-compose up`.
version: "3.4"

x-backend-config: &backend
  image: ghcr.io/osmitalia/osmit-tm-backend:v4.6.2-hotfix
  env_file: ${ENV_FILE:-tasking-manager.env}
  depends_on:
    - postgresql
  links:
    - postgresql
  networks:
    - tm-web

services:
  # Main application
  backend:
    <<: *backend
    container_name: backend
    restart: always
    labels:
      - traefik.http.routers.backend.rule=Host(`osmit-tm4.wmcloud.org`) && PathPrefix(`/api/`)
      - traefik.http.services.backend.loadbalancer.server.port=5000

  migration:
    <<: *backend
    container_name: migration
    restart: on-failure
    command: flask db upgrade

  frontend:
    image: ghcr.io/osmitalia/osmit-tm-frontend:v4.6.2-hotfix
    restart: always
    networks:
      - tm-web
    labels:
      - traefik.http.routers.frontend.rule=Host(`osmit-tm4.wmcloud.org`)
      - traefik.http.services.frontend.loadbalancer.server.port=80

  postgresql:
    image: mdillon/postgis:11
    container_name: postgresql
    restart: always
    env_file: ${ENV_FILE:-tasking-manager.env}
    networks:
      - tm-web
    volumes:
      - /srv/postgresql:/var/lib/postgresql/data

  traefik:
    image: traefik:v2.10
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
    networks:
      - tm-web

networks:
  tm-web:
    external: false
